### PR TITLE
Feature/updates for 6.4

### PR DESCRIPTION
**Pull request by FalkoHilbert**

### CODE REVIEW

**Comment by runelaenen** [comment]
Hi @FalkoHilbert 

Thank you for your contribution! Can you remove the compiled javascripts? It get's added automatically to the release zips by the GitHub actions. That's why they are not in the repo.

**Comment by FalkoHilbert** [comment]
ok, no Problem. That's why I also put it in a separate commit ;)

**Comment by FalkoHilbert** [comment]
it's away

**Comment by runelaenen** [comment]
Thank you for your contribution! I've added the tag, the release will be available shortly.

**Pull request merged**
